### ISSUE TITLE
nil image field is still crashing on dashboard index page

### ISSUE THREAD

**Issue by jesse-wang** [thoughtbot/administrate-field-image#14]
Showing /usr/local/bundle/gems/administrate-field-image-1.1.0/app/views/fields/image/_index.html.erb where line #18 raised:

nil is not a valid asset source

**Comment by nickcharlton** [comment]
Hi @jesse-wang

Can you provide a test case, or an example app where we can see this not working? Thanks!

**Comment by jesse-wang** [comment]
@nickcharlton 

It's a little hard for me to provide but I pretty much think it's because your _show.html.erb file has `<%= image_tag field.data if field.data.present? %>`

but the _index.html.erb still has `<%= image_tag field.data %>` so that in an index page a nil image will cause the problem.

**Comment by ID25** [comment]
Hi @nickcharlton 
Review this PR, fix for nil image at index page: [pull request](https://github.com/thoughtbot/administrate-field-image/pull/15)
