### ISSUE TITLE
[Feature proposal] Preview in form?

### ISSUE THREAD

**Issue by okuramasafumi** [thoughtbot/administrate-field-image#16]
It'd be really helpful to see a preview of an image when editing it.

**Comment by nickcharlton** [comment]
Are you thinking as a small box just above the editing form?

Perhaps something like this?

![screen shot 2018-04-20 at 12 17 50](https://user-images.githubusercontent.com/11917/39048304-e3ae2526-4494-11e8-9274-55649c3325ca.png)

**Comment by okuramasafumi** [comment]
Yes, I imagined preview just like you proposed.

**Comment by nickcharlton** [comment]
Do you think you'd be able to open a PR for that?

**Comment by okuramasafumi** [comment]
I've implemented super simple preview in my branch, but the problem is that the field for preview appears when creating new image. Should I also add `_edit.html.erb`?

**Comment by nickcharlton** [comment]
I'm not sure off the top of my head, but it's worth a try!

**Comment by nickcharlton** [comment]
I'm going to close this, as it's been open for years since anything happened. But if someone is keen to open a PR, I'd be more than happy to review it!
